github_repo: "dsc-courses/dsc80-2024-wi-grades.git" # <organization/personal account name>/<repo name>.git

gradescope_credentials:
  email: "ardas@ucsd.edu"
  password: "tWd2bii8qs3mSY" # make sure to delete this line before pushing to github

course_info:
  course_id: 759147
  assignment_id: 4078318
  roster_path: "../data/DSC_80_Spring_2024_grades.csv"

data_path:
  grades_filename: "../data/DSC_80_Spring_2024_grades.csv"

labs:
  num_labs: 7 # number of labs to include for the current report
  max_labs: 9 # total number of labs in this class

projects:
  num_projects: 3
  max_projects: 4
  num_checkpoints: 3
  max_checkpoints: 5

exams:
  midterm:
    enabled: true
    versions:
      - "A"
      - "B"
    bonus: 0
  final:
    enabled: false
    versions:
      - "A"
      - "B"
    bonus: 0
    container_id: 104185
    container_path: "../data/Final_Exam_Version_Set_Scores.zip"

discussions:
  num_discussions_and_lecture_attendence_required: 8

drop_policy:
  num_drops: 1
  could_drop:
    - "lab"

assignment_weights:
  lab: 0.20
  project: 0.25
  project_checkpoint: 0.05
  midterm_exam: 0.20
  final_exam: 0.30

discussion_assignment_weights:
  lab: 0.20
  project: 0.25
  project_checkpoint: 0.05
  midterm_exam: 0.185
  final_exam: 0.285
  discussion: 0.05

extra_credit:
  overall: 0.00
